import '@testing-library/jest-dom/vitest';
import { fireEvent, render, screen } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import { NextRequiredAction } from './NextRequiredAction';

describe('NextRequiredAction', () => {
  it('asks the agent for a new minimum proposal instead of implying a fixed safe action', () => {
    const onAskAgent = vi.fn();
    render(<NextRequiredAction busy={false} onAskAgent={onAskAgent} />);

    expect(screen.getByRole('heading', { name: 'Ask the agent for a minimum-scope remediation proposal' })).toBeInTheDocument();
    expect(screen.getByText(/No fallback action is generated by the application/i)).toBeInTheDocument();
    const button = screen.getByRole('button', { name: 'Ask agent for minimum proposal' });
    fireEvent.click(button);

    expect(onAskAgent).toHaveBeenCalledTimes(1);
    expect(screen.queryByText('Prepare safe path')).not.toBeInTheDocument();
  });

  it('blocks duplicate requests while the agent flow is busy', () => {
    const onAskAgent = vi.fn();
    render(<NextRequiredAction busy onAskAgent={onAskAgent} />);

    const button = screen.getByRole('button', { name: 'Ask agent for minimum proposal' });
    expect(button).toBeDisabled();
    fireEvent.click(button);
    expect(onAskAgent).not.toHaveBeenCalled();
  });
});
