import { ArrowRight, Bot } from 'lucide-react';
import { Button } from '../ui/Button';
import { Surface } from '../ui/Surface';

interface Props {
  busy: boolean;
  onAskAgent: () => void;
}

export function NextRequiredAction({ busy, onAskAgent }: Props) {
  return (
    <Surface className="next-required-action" aria-labelledby="next-required-action-title">
      <div>
        <p className="eyebrow">Try a constrained proposal</p>
        <h2 id="next-required-action-title">Ask the agent for a minimum-scope remediation proposal</h2>
        <p>The agent will propose a new action. T3N still decides whether it is safe enough to continue. No fallback action is generated by the application.</p>
      </div>
      <Button variant="primary" onClick={onAskAgent} disabled={busy}><Bot aria-hidden="true" />Ask agent for minimum proposal<ArrowRight aria-hidden="true" /></Button>
    </Surface>
  );
}
