import '@testing-library/jest-dom/vitest';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, expect, it } from 'vitest';
import { ScreenManualDialog } from './ScreenManualDialog';

describe('ScreenManualDialog', () => {
  it('traps focus and explains executive demo, human proof, private notification, business outcome, control impact, A2A, privacy and provenance', async () => {
    const user = userEvent.setup();
    render(<div><button type="button">Outside action</button><ScreenManualDialog /></div>);

    const trigger = screen.getByRole('button', { name: 'Open Screen Manual' });
    expect(trigger).toHaveAttribute('title', 'Open Screen Manual');
    expect(trigger).toHaveTextContent('Screen Manual');
    await user.click(trigger);

    const dialog = screen.getByRole('dialog', { name: 'Incident Response Dashboard' });
    const closeButton = screen.getByRole('button', { name: 'Close Screen Manual' });
    expect(dialog).toHaveAttribute('aria-modal', 'true');
    expect(screen.getByText('Screen Manual')).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Purpose' })).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Areas, fields and actions' })).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Human access and permissions' })).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Executive Demo' })).toBeInTheDocument();
    expect(dialog).toHaveTextContent(/projection of the same runtime state.*does not create a parallel incident.*authorization.*execution.*evidence path/i);
    expect(dialog).toHaveTextContent(/business problem.*observed outcome.*measured operational impact.*authority mechanism.*technical proof/i);
    expect(dialog).toHaveTextContent(/AI can propose\. Policy decides\. Humans authorize\. T3N executes\..*Trust path/i);
    expect(dialog).toHaveTextContent(/BLOCKED BEFORE PROTECTED EGRESS.*MINIMIZATION REQUIRED.*HUMAN AUTHORIZATION REQUIRED/i);
    expect(dialog).toHaveTextContent(/AUTHORIZED \/ NOT EXECUTED.*ACCEPTED \/ NOT VERIFIED/i);
    expect(dialog).toHaveTextContent(/Proof at a glance.*does not replace.*Evidence Center/i);
    expect(dialog).toHaveTextContent(/T3N LIVE \/ READY.*protected remediation ready.*valid evidence/i);
    expect(dialog).toHaveTextContent(/has no Analyze, Authorize, Execute, or Verify buttons/i);
    expect(dialog).toHaveTextContent(/does not convert operational metrics into money saved.*breaches avoided.*guaranteed compliance.*risk reduction/i);
    expect(screen.getByRole('heading', { name: 'Business Outcome' })).toBeInTheDocument();
    expect(dialog).toHaveTextContent(/Time to policy decision.*evaluatedAt.*action.createdAt/i);
    expect(dialog).toHaveTextContent(/Time to verified outcome.*completedAt.*COMPLETED/i);
    expect(dialog).toHaveTextContent(/does not calculate money saved.*ROI/i);
    expect(dialog).toHaveTextContent(/Not yet observed.*Not verified yet/i);
    expect(screen.getByRole('heading', { name: 'Measured control impact' })).toBeInTheDocument();
    expect(dialog).toHaveTextContent(/Observed block rate.*DENY.*evaluated decisions.*100/i);
    expect(dialog).toHaveTextContent(/Verified completion.*COMPLETED.*UNVERIFIED.*FAILED.*100/i);
    expect(dialog).toHaveTextContent(/Median policy decision.*evaluatedAt.*action.createdAt/i);
    expect(dialog).toHaveTextContent(/Financial ROI is NOT MEASURED/i);
    expect(dialog).toHaveTextContent(/Retained.*24 hours.*7 days/i);
    expect(screen.getByText('Identity, Member grant and effective authorization')).toBeInTheDocument();
    expect(dialog).toHaveTextContent(/checkDelegation.*authenticated client/i);
    expect(dialog).toHaveTextContent(/evaluate-action.*execute-remediation.*verify-remediation/i);
    expect(dialog).toHaveTextContent(/Confirmed.*Denied.*Unknown/i);
    expect(screen.getByText('Readiness')).toBeInTheDocument();
    expect(dialog).toHaveTextContent(/Proposal evaluation.*Protected remediation/i);
    expect(screen.getByText('Agent Card and public A2A')).toBeInTheDocument();
    expect(dialog).toHaveTextContent(/A2A.*public evaluation/i);
    expect(dialog).toHaveTextContent(/PII-free/i);
    expect(screen.getByText('Policy, minimization, human authorization and execution')).toBeInTheDocument();
    expect(dialog).toHaveTextContent(/one-time.*v2.*Ed25519/i);
    expect(dialog).toHaveTextContent(/Gateway proof check.*fail-fast.*does not replace T3N/i);
    expect(dialog).toHaveTextContent(/Before reading.*security_api_url.*security_api_key.*WASM verifies signature.*nonce/i);
    expect(dialog).toHaveTextContent(/does not claim that T3N verified the human's civil identity/i);
    expect(dialog).toHaveTextContent(/notify-security.*incident_id.*severity.*summary.*verified_email/i);
    expect(dialog).toHaveTextContent(/browser.*model.*Java backend.*gateway.*logical reference.*verified_email/i);
    expect(dialog).toHaveTextContent(/profile marker.*exclusively inside the Rust\/WASM contract/i);
    expect(dialog).toHaveTextContent(/Resolved plaintext.*protected egress.*authorized external service.*not returned/i);
    expect(dialog).toHaveTextContent(/DELIVERED.*recipient_resolved=true/i);
    expect(screen.getByText('Local audit integrity and T3N Activity Log')).toBeInTheDocument();
    expect(dialog).toHaveTextContent(/HMAC-SHA256/i);
    expect(dialog).toHaveTextContent(/tamper-evident/i);
    expect(dialog).toHaveTextContent(/VERIFIED.*BROKEN.*KEY_MISMATCH.*LEGACY_UNVERIFIED/i);
    expect(dialog).toHaveTextContent(/old internally consistent snapshot/i);
    expect(dialog).toHaveTextContent(/evaluate-action.*Proposal Agent.*execute-remediation.*verify-remediation.*Protected Executor/i);
    expect(screen.getByText('Proof & evidence')).toBeInTheDocument();
    expect(dialog).toHaveTextContent(/Source tree/i);
    expect(dialog).toHaveTextContent(/LIVE-PROFILE-PLACEHOLDER-RESOLUTION.*NOT RUN.*T3N testnet/i);
    expect(dialog).toHaveTextContent(/signed proof.*nonce.*private key.*non-secret/i);
    expect(dialog).toHaveTextContent(/COMPLETED/i);
    expect(screen.getByRole('heading', { name: 'Messages and error states' })).toBeInTheDocument();
    expect(closeButton).toHaveFocus();

    await user.tab();
    expect(closeButton).toHaveFocus();
    screen.getByRole('button', { name: 'Outside action' }).focus();
    expect(closeButton).toHaveFocus();
    await user.keyboard('{Escape}');
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
    await new Promise((resolve) => requestAnimationFrame(resolve));
    expect(trigger).toHaveFocus();
  });

  it('closes from the backdrop, restores focus and can be reopened without duplicate handlers', async () => {
    const user = userEvent.setup();
    render(<ScreenManualDialog />);
    const trigger = screen.getByRole('button', { name: 'Open Screen Manual' });
    await user.click(trigger);
    const backdrop = screen.getByRole('presentation');
    await user.pointer([{ target: backdrop, keys: '[MouseLeft>]' }, { keys: '[/MouseLeft]' }]);
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
    await new Promise((resolve) => requestAnimationFrame(resolve));
    expect(trigger).toHaveFocus();
    await user.click(trigger);
    expect(screen.getByRole('button', { name: 'Close Screen Manual' })).toHaveFocus();
    await user.keyboard('{Escape}');
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
  });
});
