package br.com.t3privacyguard.service;

import br.com.t3privacyguard.api.ApiModels.AgentAnalysisResponse;
import br.com.t3privacyguard.api.ApiModels.CreateActionRequest;
import br.com.t3privacyguard.api.ApiModels.CreateIncidentRequest;
import br.com.t3privacyguard.api.ApiModels.IncidentResponse;
import br.com.t3privacyguard.audit.AuditIntegrityService;
import br.com.t3privacyguard.domain.Severity;
import br.com.t3privacyguard.integration.GatewayAgentClient;
import br.com.t3privacyguard.integration.GatewayAgentClient.AgentProposalResult;
import br.com.t3privacyguard.privacy.IncidentDataMinimizer;
import java.util.List;
import java.util.UUID;
import org.springframework.stereotype.Service;

@Service
public class AgentAnalysisService {
    private final GatewayAgentClient agentGateway;
    private final IncidentService incidents;
    private final AuditIntegrityService auditIntegrity;
    private final IncidentDataMinimizer minimizer;

    public AgentAnalysisService(
        GatewayAgentClient agentGateway,
        IncidentService incidents,
        AuditIntegrityService auditIntegrity,
        IncidentDataMinimizer minimizer
    ) {
        this.agentGateway = agentGateway;
        this.incidents = incidents;
        this.auditIntegrity = auditIntegrity;
        this.minimizer = minimizer;
    }

    public AgentAnalysisResponse analyze(String prompt) {
        AgentProposalResult generated = propose(prompt);
        var incident = incidents.createIncident(new CreateIncidentRequest(
            "AI agent action proposal",
            Severity.CRITICAL,
            "An untrusted prompt was interpreted by the configured AI agent. The incident keeps a minimized operational description for a bounded retention period; resolved private profile values remain outside the model and application layers.",
            "AI agent " + generated.provider()
        ));
        return persistAndEvaluate(incident, generated);
    }

    public AgentAnalysisResponse analyzeExistingIncident(String incidentId, String prompt) {
        IncidentResponse incident = incidents.getIncident(incidentId);
        AgentProposalResult generated = propose(prompt);
        return persistAndEvaluate(incident, generated);
    }

    private AgentProposalResult propose(String prompt) {
        String normalized = prompt == null ? "" : prompt.trim();
        if (normalized.isBlank() || normalized.length() > 4000) {
            throw new IllegalArgumentException("Prompt must contain between 1 and 4000 characters");
        }
        return agentGateway.propose(normalized);
    }

    private AgentAnalysisResponse persistAndEvaluate(IncidentResponse incident, AgentProposalResult generated) {
        var proposal = generated.proposal();
        List<String> fields = proposal.fields() == null ? List.of() : proposal.fields();
        List<String> privateRefs = proposal.privateRefs() == null ? List.of() : proposal.privateRefs();
        var action = incidents.addAction(incident.id(), new CreateActionRequest(
            "ai-" + UUID.randomUUID(),
            proposal.action(),
            proposal.resource(),
            proposal.purpose(),
            proposal.host(),
            fields,
            privateRefs
        ));
        auditIntegrity.append(
            incident.id(),
            "AGENT_PROPOSAL_SOURCE",
            minimizer.sanitizeAuditMessage(
                "Agent proposal " + action.id()
                    + " generated by provider " + boundedMetadata(generated.provider())
                    + " model " + boundedMetadata(generated.model())
            )
        );
        var decision = incidents.evaluate(incident.id(), action.id());
        var refreshedAction = incidents.listActions(incident.id()).stream()
            .filter(item -> item.id().equals(action.id()))
            .findFirst()
            .orElse(action);
        return new AgentAnalysisResponse(generated.provider(), generated.model(), incident, refreshedAction, decision);
    }

    private static String boundedMetadata(String value) {
        if (value == null || value.isBlank()) return "unknown";
        String normalized = value.trim().replaceAll("[^a-zA-Z0-9._:/-]", "_");
        return normalized.substring(0, Math.min(normalized.length(), 120));
    }
}
