package br.com.t3privacyguard.service;

import br.com.t3privacyguard.api.ApiModels.*;
import br.com.t3privacyguard.domain.*;
import br.com.t3privacyguard.integration.*;
import br.com.t3privacyguard.integration.GatewayPolicyClient.GatewayEvaluationRequest;
import br.com.t3privacyguard.integration.GatewayRemediationClient.RemediationRequest;
import br.com.t3privacyguard.persistence.*;
import com.fasterxml.jackson.core.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.Instant;
import java.util.*;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class IncidentService {
    private final IncidentRepository incidents; private final ActionProposalRepository actions; private final PolicyDecisionRepository decisions; private final AuditEventRepository audits; private final RemediationExecutionRepository remediations; private final GatewayPolicyClient gateway; private final GatewayRemediationClient remediationGateway; private final ObjectMapper mapper;
    public IncidentService(IncidentRepository incidents,ActionProposalRepository actions,PolicyDecisionRepository decisions,AuditEventRepository audits,RemediationExecutionRepository remediations,GatewayPolicyClient gateway,GatewayRemediationClient remediationGateway,ObjectMapper mapper){this.incidents=incidents;this.actions=actions;this.decisions=decisions;this.audits=audits;this.remediations=remediations;this.gateway=gateway;this.remediationGateway=remediationGateway;this.mapper=mapper;}
    @Transactional public IncidentResponse createIncident(CreateIncidentRequest r){Instant now=Instant.now();var e=incidents.save(new IncidentEntity(UUID.randomUUID().toString(),r.title().trim(),r.severity(),r.summary().trim(),r.source().trim(),now));audit(e.getId(),"INCIDENT_CREATED","Incident created with severity "+e.getSeverity());return incidentResponse(e);}
    @Transactional(readOnly=true) public List<IncidentResponse> listIncidents(){return incidents.findAll().stream().sorted(Comparator.comparing(IncidentEntity::getCreatedAt).reversed()).map(this::incidentResponse).toList();}
    @Transactional(readOnly=true) public IncidentResponse getIncident(String id){return incidentResponse(requireIncident(id));}
    @Transactional public ActionResponse addAction(String incidentId,CreateActionRequest r){requireIncident(incidentId);if(actions.findByRequestId(r.requestId().trim()).isPresent())throw new ConflictException("requestId already exists; duplicate/replay rejected");try{var e=actions.saveAndFlush(new ActionProposalEntity(UUID.randomUUID().toString(),incidentId,r.requestId().trim(),r.action().trim(),r.resource().trim(),r.purpose().trim(),blankToNull(r.host()),writeJson(r.fields()),Instant.now()));audit(incidentId,"ACTION_PROPOSED","Action "+e.getAction()+" proposed as request "+e.getRequestId());return actionResponse(e);}catch(DataIntegrityViolationException ex){throw new ConflictException("requestId already exists; duplicate/replay rejected");}}
    @Transactional(readOnly=true) public List<ActionResponse> listActions(String incidentId){requireIncident(incidentId);return actions.findByIncidentIdOrderByCreatedAtAsc(incidentId).stream().map(this::actionResponse).toList();}
    @Transactional public DecisionResponse evaluate(String incidentId,String actionId){var a=requireAction(incidentId,actionId);var existing=decisions.findByActionProposalId(actionId);if(existing.isPresent())return decisionResponse(existing.get());var gd=gateway.evaluate(new GatewayEvaluationRequest(a.getRequestId(),a.getAction(),a.getResource(),a.getPurpose(),a.getHost(),readList(a.getFieldsJson())));if(!a.getRequestId().equals(gd.requestId()))throw new IllegalStateException("Policy decision request id mismatch");var e=decisions.save(new PolicyDecisionEntity(UUID.randomUUID().toString(),actionId,gd.decision(),safe(gd.reasonCode(),80),safe(gd.reason(),800),writeJson(gd.allowedFields()),writeJson(gd.redactedFields()),Instant.now()));a.markEvaluated();actions.save(a);audit(incidentId,"POLICY_DECISION","Policy decision "+e.getDecision()+" with reason "+e.getReasonCode());return decisionResponse(e);}
    @Transactional public RemediationAuthorizationResponse authorizeRemediation(String incidentId,String actionId){var a=requireAction(incidentId,actionId);var d=decisions.findByActionProposalId(actionId).orElseThrow(()->new ConflictException("Action must be evaluated before remediation"));if(d.getDecision()!=DecisionType.ALLOW)throw new PolicyDeniedException("Remediation requires an ALLOW policy decision");a.authorizeRemediation();actions.save(a);audit(incidentId,"REMEDIATION_AUTHORIZED","Remediation authorized for request "+a.getRequestId());return new RemediationAuthorizationResponse(incidentId,actionId,a.getRequestId(),a.getStatus().name());}
    @Transactional public RemediationExecutionResponse executeRemediation(String incidentId,String actionId){var a=requireAction(incidentId,actionId);var persisted=remediations.findByActionProposalId(actionId);if(persisted.isPresent()){var r=persisted.get();return new RemediationExecutionResponse(incidentId,actionId,r.getRequestId(),ProposalStatus.REMEDIATED.name(),r.getHttpCode(),r.getOperationId());}if(a.getStatus()!=ProposalStatus.REMEDIATION_AUTHORIZED)throw new PolicyDeniedException("Remediation must be explicitly authorized before execution");var result=remediationGateway.execute(new RemediationRequest(a.getRequestId(),a.getAction(),a.getResource(),a.getPurpose(),readList(a.getFieldsJson())));if(!a.getRequestId().equals(result.requestId()))throw new IllegalStateException("Remediation result request id mismatch");var saved=remediations.saveAndFlush(new RemediationExecutionEntity(UUID.randomUUID().toString(),actionId,result.requestId(),result.status(),result.httpCode(),safeNullable(result.operationId(),200),Instant.now()));a.markRemediated();actions.save(a);audit(incidentId,"REMEDIATION_EXECUTED","Protected remediation completed with HTTP "+saved.getHttpCode());return new RemediationExecutionResponse(incidentId,actionId,saved.getRequestId(),a.getStatus().name(),saved.getHttpCode(),saved.getOperationId());}
    @Transactional(readOnly=true) public List<AuditResponse> history(String incidentId){requireIncident(incidentId);return audits.findByIncidentIdOrderByCreatedAtAsc(incidentId).stream().map(e->new AuditResponse(e.getId(),e.getIncidentId(),e.getType(),e.getMessage(),e.getCreatedAt())).toList();}
    private IncidentEntity requireIncident(String id){return incidents.findById(id).orElseThrow(()->new IncidentNotFoundException("Incident not found"));} private ActionProposalEntity requireAction(String incidentId,String id){var a=actions.findById(id).orElseThrow(()->new IncidentNotFoundException("Action proposal not found"));if(!a.getIncidentId().equals(incidentId))throw new IncidentNotFoundException("Action proposal not found for incident");return a;}
    private void audit(String incidentId,String type,String message){audits.save(new AuditEventEntity(UUID.randomUUID().toString(),incidentId,type,safe(message,600),Instant.now()));} private IncidentResponse incidentResponse(IncidentEntity e){return new IncidentResponse(e.getId(),e.getTitle(),e.getSeverity(),e.getSummary(),e.getSource(),e.getStatus(),e.getCreatedAt());} private ActionResponse actionResponse(ActionProposalEntity e){return new ActionResponse(e.getId(),e.getIncidentId(),e.getRequestId(),e.getAction(),e.getResource(),e.getPurpose(),e.getHost(),readList(e.getFieldsJson()),e.getStatus(),e.getCreatedAt());} private DecisionResponse decisionResponse(PolicyDecisionEntity e){return new DecisionResponse(e.getId(),e.getActionProposalId(),e.getDecision(),e.getReasonCode(),e.getReason(),readList(e.getAllowedFieldsJson()),readList(e.getRedactedFieldsJson()),e.getEvaluatedAt());}
    private String writeJson(Object v){try{return mapper.writeValueAsString(v==null?List.of():v);}catch(JsonProcessingException ex){throw new IllegalArgumentException("Unable to encode request metadata",ex);}} private List<String> readList(String j){try{return mapper.readValue(j,new TypeReference<List<String>>(){});}catch(JsonProcessingException ex){throw new IllegalStateException("Stored metadata is invalid",ex);}} private static String blankToNull(String v){return v==null||v.isBlank()?null:v.trim();} private static String safe(String v,int max){String r=v==null?"":v.replaceAll("(?i)(api[_-]?key|password|private[_-]?key|token)\\s*[:=]\\s*\\S+","$1=[REDACTED]");return r.substring(0,Math.min(r.length(),max));} private static String safeNullable(String v,int max){return v==null?null:safe(v,max);}
}
